name: CI Pipeline
  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Run tests
        run: |
          pytest 
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ratshtaed/tp-flask-app:latest .

      - name: Push Docker image
        run: |
          docker push ratshtaed/tp-flask-app:latest

      - name: Notify on failure
        if: failure()  
        uses: dawidd6/action-send-mail@v3
        with:
          to: h.social74@gmail.com
          subject: 'CI Build Failed'
          body: |
            The CI build has failed. Please check the details at ${{ github.event.repository.html_url }}.
          smtp-server: smtp.example.com  
          smtp-port: 587  
          smtp-user: ${{ secrets.SMTP_USERNAME }}
          smtp-password: ${{ secrets.SMTP_PASSWORD }}

